// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attendance.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const cancelAttendance = `-- name: CancelAttendance :exec
UPDATE attendances
SET
    status = 'cancelled',
    updated_at = NOW()
WHERE
    order_id = ?
    AND event_id = ?
    AND deleted_at IS NULL
`

type CancelAttendanceParams struct {
	OrderID uint64
	EventID uint64
}

// ============================================
// UPDATE / DELETE
// ============================================
func (q *Queries) CancelAttendance(ctx context.Context, arg CancelAttendanceParams) error {
	_, err := q.db.ExecContext(ctx, cancelAttendance, arg.OrderID, arg.EventID)
	return err
}

const checkAlreadyCheckedIn = `-- name: CheckAlreadyCheckedIn :one
SELECT
    COUNT(*)
FROM
    attendances
WHERE
    order_id = ?
    AND event_id = ?
    AND status = 'checked_in'
    AND deleted_at IS NULL
`

type CheckAlreadyCheckedInParams struct {
	OrderID uint64
	EventID uint64
}

// ============================================
// VALIDATION
// ============================================
func (q *Queries) CheckAlreadyCheckedIn(ctx context.Context, arg CheckAlreadyCheckedInParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkAlreadyCheckedIn, arg.OrderID, arg.EventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const checkAlreadyCheckedInForUpdate = `-- name: CheckAlreadyCheckedInForUpdate :one
SELECT
    status = 'checked_in' AS already_checked_in
FROM
    attendances
WHERE
    order_id = ?
    AND event_id = ?
    AND deleted_at IS NULL FOR
UPDATE
`

type CheckAlreadyCheckedInForUpdateParams struct {
	OrderID uint64
	EventID uint64
}

// CHECK
func (q *Queries) CheckAlreadyCheckedInForUpdate(ctx context.Context, arg CheckAlreadyCheckedInForUpdateParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkAlreadyCheckedInForUpdate, arg.OrderID, arg.EventID)
	var already_checked_in bool
	err := row.Scan(&already_checked_in)
	return already_checked_in, err
}

const checkIn = `-- name: CheckIn :exec
INSERT INTO
    attendances (
        order_id,
        event_id,
        user_id,
        ticket_type_id,
        check_in_time,
        check_in_method,
        status,
        checked_by
    )
VALUES
    (?, ?, ?, ?, NOW(), ?, 'checked_in', ?) ON DUPLICATE KEY
UPDATE check_in_time = NOW(),
check_in_method =
VALUES
    (check_in_method),
    status = 'checked_in',
    checked_by =
VALUES
    (checked_by),
    updated_at = NOW()
`

type CheckInParams struct {
	OrderID       uint64
	EventID       uint64
	UserID        uint64
	TicketTypeID  uint64
	CheckInMethod NullAttendancesCheckInMethod
	CheckedBy     sql.NullInt64
}

// ============================================
// CREATE / CHECK-IN
// ============================================
func (q *Queries) CheckIn(ctx context.Context, arg CheckInParams) error {
	_, err := q.db.ExecContext(ctx, checkIn,
		arg.OrderID,
		arg.EventID,
		arg.UserID,
		arg.TicketTypeID,
		arg.CheckInMethod,
		arg.CheckedBy,
	)
	return err
}

const checkInByQR = `-- name: CheckInByQR :exec
INSERT INTO
    attendances (
        order_id,
        event_id,
        user_id,
        ticket_type_id,
        check_in_time,
        check_in_method,
        status,
        checked_by
    )
VALUES
    (?, ?, ?, ?, NOW(), 'qr_code', 'checked_in', ?) ON DUPLICATE KEY
UPDATE check_in_time = NOW(),
check_in_method = 'qr_code',
status = 'checked_in',
checked_by =
VALUES
    (checked_by),
    updated_at = NOW()
`

type CheckInByQRParams struct {
	OrderID      uint64
	EventID      uint64
	UserID       uint64
	TicketTypeID uint64
	CheckedBy    sql.NullInt64
}

func (q *Queries) CheckInByQR(ctx context.Context, arg CheckInByQRParams) error {
	_, err := q.db.ExecContext(ctx, checkInByQR,
		arg.OrderID,
		arg.EventID,
		arg.UserID,
		arg.TicketTypeID,
		arg.CheckedBy,
	)
	return err
}

const checkInByQRInsertOnly = `-- name: CheckInByQRInsertOnly :exec
INSERT INTO
    attendances (
        order_id,
        event_id,
        user_id,
        ticket_type_id,
        check_in_time,
        check_in_method,
        status,
        checked_by
    )
VALUES
    (?, ?, ?, ?, NOW(), 'qr_code', 'checked_in', ?)
`

type CheckInByQRInsertOnlyParams struct {
	OrderID      uint64
	EventID      uint64
	UserID       uint64
	TicketTypeID uint64
	CheckedBy    sql.NullInt64
}

func (q *Queries) CheckInByQRInsertOnly(ctx context.Context, arg CheckInByQRInsertOnlyParams) error {
	_, err := q.db.ExecContext(ctx, checkInByQRInsertOnly,
		arg.OrderID,
		arg.EventID,
		arg.UserID,
		arg.TicketTypeID,
		arg.CheckedBy,
	)
	return err
}

const countAttendeesByEvent = `-- name: CountAttendeesByEvent :one
SELECT
    COUNT(DISTINCT user_id)
FROM
    attendances
WHERE
    event_id = ?
    AND status = 'checked_in'
    AND deleted_at IS NULL
`

// ============================================
// STATISTICS
// ============================================
func (q *Queries) CountAttendeesByEvent(ctx context.Context, eventID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAttendeesByEvent, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAttendeesByOrganizer = `-- name: CountAttendeesByOrganizer :one
SELECT
    COUNT(DISTINCT a.user_id)
FROM
    attendances a
    JOIN events e ON a.event_id = e.id
WHERE
    e.user_id = ?
    AND a.status = 'checked_in'
    AND a.deleted_at IS NULL
`

func (q *Queries) CountAttendeesByOrganizer(ctx context.Context, userID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAttendeesByOrganizer, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAttendeesByTicketType = `-- name: CountAttendeesByTicketType :one
SELECT
    COUNT(*)
FROM
    attendances
WHERE
    ticket_type_id = ?
    AND status = 'checked_in'
    AND deleted_at IS NULL
`

func (q *Queries) CountAttendeesByTicketType(ctx context.Context, ticketTypeID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAttendeesByTicketType, ticketTypeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAttendanceByEventID = `-- name: GetAttendanceByEventID :many
SELECT
    a.id,
    a.order_id,
    a.user_id,
    u.name AS user_name,
    u.email AS user_email,
    a.check_in_time,
    a.check_in_method,
    a.status,
    a.checked_by,
    c.name AS checked_by_name
FROM
    attendances a
    JOIN users u ON a.user_id = u.id
    LEFT JOIN users c ON a.checked_by = c.id
WHERE
    a.event_id = ?
    AND a.status = 'checked_in'
    AND a.deleted_at IS NULL
ORDER BY
    a.check_in_time DESC
`

type GetAttendanceByEventIDRow struct {
	ID            int64
	OrderID       uint64
	UserID        uint64
	UserName      string
	UserEmail     string
	CheckInTime   sql.NullTime
	CheckInMethod NullAttendancesCheckInMethod
	Status        NullAttendancesStatus
	CheckedBy     sql.NullInt64
	CheckedByName sql.NullString
}

func (q *Queries) GetAttendanceByEventID(ctx context.Context, eventID uint64) ([]GetAttendanceByEventIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAttendanceByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendanceByEventIDRow
	for rows.Next() {
		var i GetAttendanceByEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.CheckInTime,
			&i.CheckInMethod,
			&i.Status,
			&i.CheckedBy,
			&i.CheckedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendanceByOrderID = `-- name: GetAttendanceByOrderID :one
SELECT
    a.id,
    a.order_id,
    a.event_id,
    a.user_id,
    a.ticket_type_id,
    a.check_in_time,
    a.check_in_method,
    a.status,
    a.checked_by,
    a.created_at,
    a.updated_at,
    u.name AS user_name,
    u.email AS user_email,
    e.title AS event_title,
    tt.name AS ticket_type_name,
    c.name AS checked_by_name
FROM
    attendances a
    JOIN users u ON a.user_id = u.id
    JOIN events e ON a.event_id = e.id
    JOIN ticket_types tt ON a.ticket_type_id = tt.id
    LEFT JOIN users c ON a.checked_by = c.id
WHERE
    a.order_id = ?
    AND a.deleted_at IS NULL
`

type GetAttendanceByOrderIDRow struct {
	ID             int64
	OrderID        uint64
	EventID        uint64
	UserID         uint64
	TicketTypeID   uint64
	CheckInTime    sql.NullTime
	CheckInMethod  NullAttendancesCheckInMethod
	Status         NullAttendancesStatus
	CheckedBy      sql.NullInt64
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	UserName       string
	UserEmail      string
	EventTitle     string
	TicketTypeName string
	CheckedByName  sql.NullString
}

// ============================================
// READ
// ============================================
func (q *Queries) GetAttendanceByOrderID(ctx context.Context, orderID uint64) (GetAttendanceByOrderIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAttendanceByOrderID, orderID)
	var i GetAttendanceByOrderIDRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.EventID,
		&i.UserID,
		&i.TicketTypeID,
		&i.CheckInTime,
		&i.CheckInMethod,
		&i.Status,
		&i.CheckedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.UserEmail,
		&i.EventTitle,
		&i.TicketTypeName,
		&i.CheckedByName,
	)
	return i, err
}

const getAttendanceByUserID = `-- name: GetAttendanceByUserID :many
SELECT
    a.id,
    a.order_id,
    a.event_id,
    a.user_id,
    a.ticket_type_id,
    a.check_in_time,
    a.check_in_method,
    a.status,
    a.checked_by,
    a.created_at,
    e.title AS event_title,
    e.start_time,
    e.end_time
FROM
    attendances a
    JOIN events e ON a.event_id = e.id
WHERE
    a.user_id = ?
    AND a.deleted_at IS NULL
ORDER BY
    a.check_in_time DESC
`

type GetAttendanceByUserIDRow struct {
	ID            int64
	OrderID       uint64
	EventID       uint64
	UserID        uint64
	TicketTypeID  uint64
	CheckInTime   sql.NullTime
	CheckInMethod NullAttendancesCheckInMethod
	Status        NullAttendancesStatus
	CheckedBy     sql.NullInt64
	CreatedAt     sql.NullTime
	EventTitle    string
	StartTime     time.Time
	EndTime       time.Time
}

func (q *Queries) GetAttendanceByUserID(ctx context.Context, userID uint64) ([]GetAttendanceByUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAttendanceByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttendanceByUserIDRow
	for rows.Next() {
		var i GetAttendanceByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.EventID,
			&i.UserID,
			&i.TicketTypeID,
			&i.CheckInTime,
			&i.CheckInMethod,
			&i.Status,
			&i.CheckedBy,
			&i.CreatedAt,
			&i.EventTitle,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCheckInTimeline = `-- name: GetCheckInTimeline :many
SELECT
    HOUR (check_in_time) AS hour,
    COUNT(*) AS count
FROM
    attendances
WHERE
    event_id = ?
    AND status = 'checked_in'
    AND deleted_at IS NULL
GROUP BY
    HOUR (check_in_time)
ORDER BY
    hour ASC
`

type GetCheckInTimelineRow struct {
	Hour  int32
	Count int64
}

func (q *Queries) GetCheckInTimeline(ctx context.Context, eventID uint64) ([]GetCheckInTimelineRow, error) {
	rows, err := q.db.QueryContext(ctx, getCheckInTimeline, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCheckInTimelineRow
	for rows.Next() {
		var i GetCheckInTimelineRow
		if err := rows.Scan(&i.Hour, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCheckInTimelineByDate = `-- name: GetCheckInTimelineByDate :many
SELECT
    DATE (check_in_time) AS date,
    COUNT(*) AS count
FROM
    attendances
WHERE
    event_id = ?
    AND status = 'checked_in'
    AND deleted_at IS NULL
GROUP BY
    DATE (check_in_time)
ORDER BY
    date ASC
`

type GetCheckInTimelineByDateRow struct {
	Date  time.Time
	Count int64
}

func (q *Queries) GetCheckInTimelineByDate(ctx context.Context, eventID uint64) ([]GetCheckInTimelineByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getCheckInTimelineByDate, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCheckInTimelineByDateRow
	for rows.Next() {
		var i GetCheckInTimelineByDateRow
		if err := rows.Scan(&i.Date, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventAttendanceRate = `-- name: GetEventAttendanceRate :many
SELECT
    e.id AS event_id,
    e.title AS event_title,
    COUNT(DISTINCT o.id) AS total_orders,
    COUNT(DISTINCT a.user_id) AS attended,
    ROUND(
        COALESCE(
            COUNT(DISTINCT a.user_id) / NULLIF(COUNT(DISTINCT o.id), 0) * 100,
            0
        ),
        2
    ) AS attendance_rate
FROM
    events e
    LEFT JOIN orders o ON o.event_id = e.id
    AND o.status = 'paid'
    AND o.deleted_at IS NULL
    LEFT JOIN attendances a ON a.event_id = e.id
    AND a.status = 'checked_in'
    AND a.deleted_at IS NULL
WHERE
    e.user_id = ?
    AND e.deleted_at IS NULL
GROUP BY
    e.id,
    e.title
ORDER BY
    attendance_rate DESC
`

type GetEventAttendanceRateRow struct {
	EventID        uint64
	EventTitle     string
	TotalOrders    int64
	Attended       int64
	AttendanceRate float64
}

func (q *Queries) GetEventAttendanceRate(ctx context.Context, userID uint64) ([]GetEventAttendanceRateRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventAttendanceRate, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventAttendanceRateRow
	for rows.Next() {
		var i GetEventAttendanceRateRow
		if err := rows.Scan(
			&i.EventID,
			&i.EventTitle,
			&i.TotalOrders,
			&i.Attended,
			&i.AttendanceRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventTimeRange = `-- name: GetEventTimeRange :one
SELECT
    start_time,
    end_time
FROM
    events
WHERE
    id = ?
    AND deleted_at IS NULL
`

type GetEventTimeRangeRow struct {
	StartTime time.Time
	EndTime   time.Time
}

func (q *Queries) GetEventTimeRange(ctx context.Context, id uint64) (GetEventTimeRangeRow, error) {
	row := q.db.QueryRowContext(ctx, getEventTimeRange, id)
	var i GetEventTimeRangeRow
	err := row.Scan(&i.StartTime, &i.EndTime)
	return i, err
}

const getOrderItemDetail = `-- name: GetOrderItemDetail :one
SELECT
    oi.order_id,
    oi.event_id,
    oi.ticket_type_id,
    o.user_id
FROM
    order_items oi
    JOIN orders o ON o.id = oi.order_id
WHERE
    oi.id = ?
`

type GetOrderItemDetailRow struct {
	OrderID      uint64
	EventID      uint64
	TicketTypeID uint64
	UserID       uint64
}

func (q *Queries) GetOrderItemDetail(ctx context.Context, id uint64) (GetOrderItemDetailRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderItemDetail, id)
	var i GetOrderItemDetailRow
	err := row.Scan(
		&i.OrderID,
		&i.EventID,
		&i.TicketTypeID,
		&i.UserID,
	)
	return i, err
}

const getOrderStatus = `-- name: GetOrderStatus :one
SELECT
    status
FROM
    orders
WHERE
    id = ?
    AND deleted_at IS NULL
`

func (q *Queries) GetOrderStatus(ctx context.Context, id uint64) (OrdersStatus, error) {
	row := q.db.QueryRowContext(ctx, getOrderStatus, id)
	var status OrdersStatus
	err := row.Scan(&status)
	return status, err
}

const manualCheckIn = `-- name: ManualCheckIn :exec
INSERT INTO
    attendances (
        order_id,
        event_id,
        user_id,
        ticket_type_id,
        check_in_time,
        check_in_method,
        status,
        checked_by
    )
VALUES
    (?, ?, ?, ?, NOW(), 'manual', 'checked_in', ?) ON DUPLICATE KEY
UPDATE check_in_time = NOW(),
check_in_method = 'manual',
status = 'checked_in',
checked_by =
VALUES
    (checked_by),
    updated_at = NOW()
`

type ManualCheckInParams struct {
	OrderID      uint64
	EventID      uint64
	UserID       uint64
	TicketTypeID uint64
	CheckedBy    sql.NullInt64
}

func (q *Queries) ManualCheckIn(ctx context.Context, arg ManualCheckInParams) error {
	_, err := q.db.ExecContext(ctx, manualCheckIn,
		arg.OrderID,
		arg.EventID,
		arg.UserID,
		arg.TicketTypeID,
		arg.CheckedBy,
	)
	return err
}

const softDeleteAttendance = `-- name: SoftDeleteAttendance :exec
UPDATE attendances
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE
    id = ?
`

func (q *Queries) SoftDeleteAttendance(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteAttendance, id)
	return err
}
