// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const countCategories = `-- name: CountCategories :one
SELECT COUNT(*) FROM categories WHERE deleted_at IS NULL
`

func (q *Queries) CountCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :execresult
INSERT INTO
    categories (name, slug)
VALUES
    (?, ?)
`

type CreateCategoryParams struct {
	Name string
	Slug string
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCategory, arg.Name, arg.Slug)
}

const deleteCategory = `-- name: DeleteCategory :exec
UPDATE categories
SET
    deleted_at = NOW()
WHERE
    id = ?
`

// Soft Delete: Cukup update timestamp deleted_at
func (q *Queries) DeleteCategory(ctx context.Context, id uint32) error {
	_, err := q.db.ExecContext(ctx, deleteCategory, id)
	return err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT
    id,
    name,
    slug,
    created_at,
    updated_at
FROM
    categories
WHERE
    id = ?
    AND deleted_at IS NULL
LIMIT
    1
`

type GetCategoryByIDRow struct {
	ID        uint32
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetCategoryByID(ctx context.Context, id uint32) (GetCategoryByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i GetCategoryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT
    id,
    name,
    slug,
    created_at,
    updated_at
FROM
    categories
WHERE
    name = ?
    AND deleted_at IS NULL
LIMIT
    1
`

type GetCategoryByNameRow struct {
	ID        uint32
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (GetCategoryByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByName, name)
	var i GetCategoryByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT
    id,
    name,
    slug,
    created_at,
    updated_at
FROM
    categories
WHERE
    deleted_at IS NULL
ORDER BY
    name ASC
LIMIT ? OFFSET ?
`

type ListCategoriesParams struct {
	Limit  int32
	Offset int32
}

type ListCategoriesRow struct {
	ID        uint32
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]ListCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories
SET
    name = ?,
    slug = ?
WHERE
    id = ?
    AND deleted_at IS NULL
`

type UpdateCategoryParams struct {
	Name string
	Slug string
	ID   uint32
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory, arg.Name, arg.Slug, arg.ID)
	return err
}
