// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard_organizer.sql

package database

import (
	"context"
	"database/sql"
)

const countEventsActiveByOrganizer = `-- name: CountEventsActiveByOrganizer :one
SELECT COUNT(*) FROM events 
WHERE user_id = ? AND status = 'active' AND deleted_at IS NULL
`

// 2. Total Event Active
func (q *Queries) CountEventsActiveByOrganizer(ctx context.Context, userID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventsActiveByOrganizer, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsByOrganizer = `-- name: CountEventsByOrganizer :one
SELECT COUNT(*) FROM events 
WHERE user_id = ? AND deleted_at IS NULL
`

// 1. Total Event
func (q *Queries) CountEventsByOrganizer(ctx context.Context, userID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventsByOrganizer, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersByOrganizer = `-- name: CountOrdersByOrganizer :one
SELECT COUNT(*) FROM orders o
JOIN events e ON o.event_id = e.id
WHERE e.user_id = ? AND o.deleted_at IS NULL
`

// 3. Total Orders dari Event Organizer
func (q *Queries) CountOrdersByOrganizer(ctx context.Context, userID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrdersByOrganizer, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const recentOrdersByOrganizer = `-- name: RecentOrdersByOrganizer :many
SELECT
    o.id AS order_id,
    e.id AS event_id,
    e.title AS event_title,
    u.id AS user_id,
    u.name AS user_name,
    u.email AS user_email,
    o.total_amount,
    o.status,
    o.created_at
FROM orders o
JOIN events e ON o.event_id = e.id
JOIN users u ON o.user_id = u.id
WHERE e.user_id = ? AND o.deleted_at IS NULL
ORDER BY o.created_at DESC
LIMIT ?
`

type RecentOrdersByOrganizerParams struct {
	UserID uint64
	Limit  int32
}

type RecentOrdersByOrganizerRow struct {
	OrderID     uint64
	EventID     uint64
	EventTitle  string
	UserID      uint64
	UserName    string
	UserEmail   string
	TotalAmount uint32
	Status      OrdersStatus
	CreatedAt   sql.NullTime
}

// 7. Recent Orders (Organizer)
func (q *Queries) RecentOrdersByOrganizer(ctx context.Context, arg RecentOrdersByOrganizerParams) ([]RecentOrdersByOrganizerRow, error) {
	rows, err := q.db.QueryContext(ctx, recentOrdersByOrganizer, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecentOrdersByOrganizerRow
	for rows.Next() {
		var i RecentOrdersByOrganizerRow
		if err := rows.Scan(
			&i.OrderID,
			&i.EventID,
			&i.EventTitle,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenuePerEventByOrganizer = `-- name: RevenuePerEventByOrganizer :many
SELECT
    e.id AS event_id,
    e.title AS event_title,
    COUNT(o.id) AS total_orders,
    COALESCE(SUM(o.total_amount), 0) AS revenue
FROM events e
LEFT JOIN orders o ON o.event_id = e.id AND o.status = 'paid' AND o.deleted_at IS NULL
WHERE e.user_id = ? AND e.deleted_at IS NULL
GROUP BY e.id, e.title
ORDER BY revenue DESC
`

type RevenuePerEventByOrganizerRow struct {
	EventID     uint64
	EventTitle  string
	TotalOrders int64
	Revenue     interface{}
}

// 6. Revenue Per Event (Organizer)
func (q *Queries) RevenuePerEventByOrganizer(ctx context.Context, userID uint64) ([]RevenuePerEventByOrganizerRow, error) {
	rows, err := q.db.QueryContext(ctx, revenuePerEventByOrganizer, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevenuePerEventByOrganizerRow
	for rows.Next() {
		var i RevenuePerEventByOrganizerRow
		if err := rows.Scan(
			&i.EventID,
			&i.EventTitle,
			&i.TotalOrders,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenuePerMonthByOrganizer = `-- name: RevenuePerMonthByOrganizer :many
SELECT
    YEAR(o.created_at) AS year,
    MONTH(o.created_at) AS month,
    COALESCE(SUM(o.total_amount), 0) AS revenue
FROM orders o
JOIN events e ON o.event_id = e.id
WHERE e.user_id = ? 
    AND o.status = 'paid' 
    AND YEAR(o.created_at) = ?
    AND o.deleted_at IS NULL
GROUP BY YEAR(o.created_at), MONTH(o.created_at)
ORDER BY YEAR(o.created_at), MONTH(o.created_at)
`

type RevenuePerMonthByOrganizerParams struct {
	UserID    uint64
	CreatedAt sql.NullTime
}

type RevenuePerMonthByOrganizerRow struct {
	Year    int32
	Month   int32
	Revenue interface{}
}

// 5. Revenue Per Month (Organizer)
func (q *Queries) RevenuePerMonthByOrganizer(ctx context.Context, arg RevenuePerMonthByOrganizerParams) ([]RevenuePerMonthByOrganizerRow, error) {
	rows, err := q.db.QueryContext(ctx, revenuePerMonthByOrganizer, arg.UserID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevenuePerMonthByOrganizerRow
	for rows.Next() {
		var i RevenuePerMonthByOrganizerRow
		if err := rows.Scan(&i.Year, &i.Month, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topEventsByOrganizer = `-- name: TopEventsByOrganizer :many
SELECT
    e.id AS event_id,
    e.title,
    COUNT(o.id) AS total_orders,
    COALESCE(SUM(o.total_amount), 0) AS revenue,
    COUNT(DISTINCT o.user_id) AS attendees
FROM events e
LEFT JOIN orders o ON o.event_id = e.id AND o.status = 'paid' AND o.deleted_at IS NULL
WHERE e.user_id = ? AND e.deleted_at IS NULL
GROUP BY e.id, e.title
ORDER BY revenue DESC
LIMIT ?
`

type TopEventsByOrganizerParams struct {
	UserID uint64
	Limit  int32
}

type TopEventsByOrganizerRow struct {
	EventID     uint64
	Title       string
	TotalOrders int64
	Revenue     interface{}
	Attendees   int64
}

// 8. Top Events (Organizer)
func (q *Queries) TopEventsByOrganizer(ctx context.Context, arg TopEventsByOrganizerParams) ([]TopEventsByOrganizerRow, error) {
	rows, err := q.db.QueryContext(ctx, topEventsByOrganizer, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopEventsByOrganizerRow
	for rows.Next() {
		var i TopEventsByOrganizerRow
		if err := rows.Scan(
			&i.EventID,
			&i.Title,
			&i.TotalOrders,
			&i.Revenue,
			&i.Attendees,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalRevenueByOrganizer = `-- name: TotalRevenueByOrganizer :one
SELECT COALESCE(SUM(o.total_amount), 0) FROM orders o
JOIN events e ON o.event_id = e.id
WHERE e.user_id = ? AND o.status = 'paid' AND o.deleted_at IS NULL
`

// 4. Total Revenue Organizer
func (q *Queries) TotalRevenueByOrganizer(ctx context.Context, userID uint64) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, totalRevenueByOrganizer, userID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}
