// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard_admin.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const revenuePerDateRange = `-- name: RevenuePerDateRange :many
SELECT
    DATE(created_at) AS date,
    CAST(COALESCE(SUM(amount), 0)AS SIGNED) AS revenue
FROM
    payments
WHERE
    status = 'paid'
    AND deleted_at IS NULL
    AND created_at BETWEEN ? AND ?
GROUP BY
    DATE(created_at)
ORDER BY
    DATE(created_at)
`

type RevenuePerDateRangeParams struct {
	FromCreatedAt sql.NullTime
	ToCreatedAt   sql.NullTime
}

type RevenuePerDateRangeRow struct {
	Date    time.Time
	Revenue int64
}

func (q *Queries) RevenuePerDateRange(ctx context.Context, arg RevenuePerDateRangeParams) ([]RevenuePerDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, revenuePerDateRange, arg.FromCreatedAt, arg.ToCreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevenuePerDateRangeRow
	for rows.Next() {
		var i RevenuePerDateRangeRow
		if err := rows.Scan(&i.Date, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenuePerMonth = `-- name: RevenuePerMonth :many
SELECT
    YEAR(created_at) AS year,
    MONTH(created_at) AS month,
    CAST(COALESCE(SUM(amount), 0)AS SIGNED) AS revenue
FROM
    payments
WHERE
    status = 'paid'
    AND YEAR(created_at) = ?
    AND deleted_at IS NULL
GROUP BY
    YEAR(created_at),
    MONTH(created_at)
ORDER BY
    YEAR(created_at),
    MONTH(created_at)
`

type RevenuePerMonthRow struct {
	Year    int32
	Month   int32
	Revenue int64
}

func (q *Queries) RevenuePerMonth(ctx context.Context, createdAt sql.NullTime) ([]RevenuePerMonthRow, error) {
	rows, err := q.db.QueryContext(ctx, revenuePerMonth, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevenuePerMonthRow
	for rows.Next() {
		var i RevenuePerMonthRow
		if err := rows.Scan(&i.Year, &i.Month, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenuePerWeek = `-- name: RevenuePerWeek :many
SELECT
    YEAR(created_at) AS year,
    WEEK(created_at, 1) AS week,
    CAST(COALESCE(SUM(amount), 0)AS SIGNED) AS revenue
FROM
    payments
WHERE
    status = 'paid'
    AND YEAR(created_at) = ?
    AND deleted_at IS NULL
GROUP BY
    YEAR(created_at),
    WEEK(created_at, 1)
ORDER BY
    YEAR(created_at),
    WEEK(created_at, 1)
`

type RevenuePerWeekRow struct {
	Year    int32
	Week    int32
	Revenue int64
}

func (q *Queries) RevenuePerWeek(ctx context.Context, createdAt sql.NullTime) ([]RevenuePerWeekRow, error) {
	rows, err := q.db.QueryContext(ctx, revenuePerWeek, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevenuePerWeekRow
	for rows.Next() {
		var i RevenuePerWeekRow
		if err := rows.Scan(&i.Year, &i.Week, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenuePerYear = `-- name: RevenuePerYear :many
SELECT
    YEAR(created_at) AS year,
    CAST(COALESCE(SUM(amount), 0)AS SIGNED) AS revenue
FROM
    payments
WHERE
    status = 'paid'
    AND deleted_at IS NULL
GROUP BY
    YEAR(created_at)
ORDER BY
    YEAR(created_at)
`

type RevenuePerYearRow struct {
	Year    int32
	Revenue int64
}

func (q *Queries) RevenuePerYear(ctx context.Context) ([]RevenuePerYearRow, error) {
	rows, err := q.db.QueryContext(ctx, revenuePerYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevenuePerYearRow
	for rows.Next() {
		var i RevenuePerYearRow
		if err := rows.Scan(&i.Year, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumRevenue = `-- name: SumRevenue :one
SELECT
    CAST(COALESCE(SUM(amount), 0)AS SIGNED) AS total
FROM
    payments
WHERE
    status = 'paid'
    AND deleted_at IS NULL
`

func (q *Queries) SumRevenue(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumRevenue)
	var total int64
	err := row.Scan(&total)
	return total, err
}
