// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createEvent = `-- name: CreateEvent :execresult
INSERT INTO
    events (
        category_id,
        user_id,
        title,
        description,
        location,
        start_time,
        end_time,
        price,
        quota,
        status
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	CategoryID  uint32
	UserID      uint64
	Title       string
	Description string
	Location    string
	StartTime   time.Time
	EndTime     time.Time
	Price       sql.NullString
	Quota       int32
	Status      NullEventsStatus
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEvent,
		arg.CategoryID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.Price,
		arg.Quota,
		arg.Status,
	)
}

const deleteEvent = `-- name: DeleteEvent :exec
UPDATE events
SET
    deleted_at = NOW()
WHERE
    id = ?
`

// Soft Delete Event
func (q *Queries) DeleteEvent(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT
    e.id,
    e.category_id,
    e.user_id,
    e.title,
    e.description,
    e.location,
    e.start_time,
    e.end_time,
    e.price,
    e.quota,
    e.status,
    e.created_at,
    c.name AS category_name,
    u.name AS organizer_name,
    (
        e.quota - (
            SELECT
                COUNT(*)
            FROM
                tickets t
            WHERE
                t.event_id = e.id
                AND t.status = 'paid'
                AND t.deleted_at IS NULL
        )
    ) AS available_quota
FROM
    events e
    JOIN categories c ON e.category_id = c.id
    JOIN users u ON e.user_id = u.id
WHERE
    e.id = ?
    AND e.deleted_at IS NULL
LIMIT
    1
`

type GetEventByIDRow struct {
	ID             uint64
	CategoryID     uint32
	UserID         uint64
	Title          string
	Description    string
	Location       string
	StartTime      time.Time
	EndTime        time.Time
	Price          sql.NullString
	Quota          int32
	Status         NullEventsStatus
	CreatedAt      sql.NullTime
	CategoryName   string
	OrganizerName  string
	AvailableQuota int32
}

func (q *Queries) GetEventByID(ctx context.Context, id uint64) (GetEventByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.Price,
		&i.Quota,
		&i.Status,
		&i.CreatedAt,
		&i.CategoryName,
		&i.OrganizerName,
		&i.AvailableQuota,
	)
	return i, err
}

const listEventsActive = `-- name: ListEventsActive :many
SELECT
    e.id,
    e.title,
    e.description,
    e.location,
    e.start_time,
    e.end_time,
    e.price,
    e.quota,
    e.status,
    e.created_at,
    c.name AS category_name,
    u.name AS organizer_name,
    -- Menghitung sisa tiket secara real-time dari tiket yang berstatus 'paid'
    (
        e.quota - (
            SELECT
                COUNT(*)
            FROM
                tickets t
            WHERE
                t.event_id = e.id
                AND t.status = 'paid'
                AND t.deleted_at IS NULL
        )
    ) AS available_quota
FROM
    events e
    JOIN categories c ON e.category_id = c.id
    JOIN users u ON e.user_id = u.id
WHERE
    e.status = 'active'
    AND e.end_time > NOW()
    AND e.deleted_at IS NULL
    AND c.deleted_at IS NULL
ORDER BY
    e.start_time ASC
`

type ListEventsActiveRow struct {
	ID             uint64
	Title          string
	Description    string
	Location       string
	StartTime      time.Time
	EndTime        time.Time
	Price          sql.NullString
	Quota          int32
	Status         NullEventsStatus
	CreatedAt      sql.NullTime
	CategoryName   string
	OrganizerName  string
	AvailableQuota int32
}

// Hanya menampilkan event yang aktif, belum kedaluwarsa, dan belum di-soft delete
func (q *Queries) ListEventsActive(ctx context.Context) ([]ListEventsActiveRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsActiveRow
	for rows.Next() {
		var i ListEventsActiveRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.Price,
			&i.Quota,
			&i.Status,
			&i.CreatedAt,
			&i.CategoryName,
			&i.OrganizerName,
			&i.AvailableQuota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE events
SET
    category_id = ?,
    title = ?,
    description = ?,
    location = ?,
    start_time = ?,
    end_time = ?,
    price = ?,
    quota = ?,
    status = ?
WHERE
    id = ?
    AND deleted_at IS NULL
`

type UpdateEventParams struct {
	CategoryID  uint32
	Title       string
	Description string
	Location    string
	StartTime   time.Time
	EndTime     time.Time
	Price       sql.NullString
	Quota       int32
	Status      NullEventsStatus
	ID          uint64
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.ExecContext(ctx, updateEvent,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.Price,
		arg.Quota,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateEventStatus = `-- name: UpdateEventStatus :exec
UPDATE events
SET
    status = ?
WHERE
    id = ?
    AND deleted_at IS NULL
`

type UpdateEventStatusParams struct {
	Status NullEventsStatus
	ID     uint64
}

// Dipakai khusus untuk pembatalan (cancel) event oleh admin/organizer
func (q *Queries) UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateEventStatus, arg.Status, arg.ID)
	return err
}
