// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event_media.sql

package database

import (
	"context"
	"database/sql"
)

const createEventMedia = `-- name: CreateEventMedia :execresult
INSERT INTO
    event_media (event_id, image_path, is_primary)
VALUES
    (?, ?, ?)
`

type CreateEventMediaParams struct {
	EventID   uint64
	ImagePath string
	IsPrimary sql.NullBool
}

func (q *Queries) CreateEventMedia(ctx context.Context, arg CreateEventMediaParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEventMedia, arg.EventID, arg.ImagePath, arg.IsPrimary)
}

const deleteEventMedia = `-- name: DeleteEventMedia :exec
DELETE FROM event_media
WHERE
    id = ?
`

func (q *Queries) DeleteEventMedia(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteEventMedia, id)
	return err
}

const getEventMediaByID = `-- name: GetEventMediaByID :one
SELECT
    id,
    event_id,
    image_path,
    is_primary,
    created_at
FROM event_media
WHERE
    id = ?
LIMIT 1
`

func (q *Queries) GetEventMediaByID(ctx context.Context, id uint64) (EventMedium, error) {
	row := q.db.QueryRowContext(ctx, getEventMediaByID, id)
	var i EventMedium
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ImagePath,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const getEventPrimaryMedia = `-- name: GetEventPrimaryMedia :one
SELECT
    id,
    event_id,
    image_path,
    is_primary,
    created_at
FROM
    event_media
WHERE
    event_id = ?
    AND is_primary = TRUE
LIMIT
    1
`

func (q *Queries) GetEventPrimaryMedia(ctx context.Context, eventID uint64) (EventMedium, error) {
	row := q.db.QueryRowContext(ctx, getEventPrimaryMedia, eventID)
	var i EventMedium
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ImagePath,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const listEventMedia = `-- name: ListEventMedia :many
SELECT
    id,
    event_id,
    image_path,
    is_primary,
    created_at
FROM
    event_media
WHERE
    event_id = ?
ORDER BY
    is_primary DESC,
    created_at ASC
`

func (q *Queries) ListEventMedia(ctx context.Context, eventID uint64) ([]EventMedium, error) {
	rows, err := q.db.QueryContext(ctx, listEventMedia, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventMedium
	for rows.Next() {
		var i EventMedium
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ImagePath,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetEventPrimaryMedia = `-- name: ResetEventPrimaryMedia :exec
UPDATE event_media
SET
    is_primary = FALSE
WHERE
    event_id = ?
`

func (q *Queries) ResetEventPrimaryMedia(ctx context.Context, eventID uint64) error {
	_, err := q.db.ExecContext(ctx, resetEventPrimaryMedia, eventID)
	return err
}

const setEventPrimaryMedia = `-- name: SetEventPrimaryMedia :exec
UPDATE event_media
SET
    is_primary = TRUE
WHERE
    id = ?
    AND event_id = ?
`

type SetEventPrimaryMediaParams struct {
	ID      uint64
	EventID uint64
}

func (q *Queries) SetEventPrimaryMedia(ctx context.Context, arg SetEventPrimaryMediaParams) error {
	_, err := q.db.ExecContext(ctx, setEventPrimaryMedia, arg.ID, arg.EventID)
	return err
}
