// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: event.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const countEventsByStatus = `-- name: CountEventsByStatus :one
SELECT
    COUNT(*)
FROM
    events e
    JOIN categories c ON e.category_id = c.id
WHERE
    e.status = ?
    AND e.deleted_at IS NULL
    AND c.deleted_at IS NULL
`

func (q *Queries) CountEventsByStatus(ctx context.Context, status NullEventsStatus) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMyEvents = `-- name: CountMyEvents :one
SELECT
    COUNT(*)
FROM
    events e
WHERE
    e.user_id = ?
    AND e.deleted_at IS NULL
`

func (q *Queries) CountMyEvents(ctx context.Context, userID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMyEvents, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :execresult
INSERT INTO
    events (
        category_id,
        user_id,
        title,
        description,
        location,
        start_time,
        end_time,
        status
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	CategoryID  uint32
	UserID      uint64
	Title       string
	Description string
	Location    string
	StartTime   time.Time
	EndTime     time.Time
	Status      NullEventsStatus
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEvent,
		arg.CategoryID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
	)
}

const deleteEvent = `-- name: DeleteEvent :exec
UPDATE events
SET
    deleted_at = NOW
WHERE
    id = ?
`

// Soft Delete Event
func (q *Queries) DeleteEvent(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteEvent, id)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT
    e.id,
    e.category_id,
    e.user_id,
    e.title,
    e.description,
    e.location,
    e.start_time,
    e.end_time,
    e.status,
    e.created_at,
    c.name AS category_name,
    u.name AS organizer_name,
    -- 1. Hitung total kuota asli dari semua ticket_types di event ini
    COALESCE(
        (
            SELECT
                SUM(tt.quota)
            FROM
                ticket_types tt
            WHERE
                tt.event_id = e.id
        ),
        0
    ) -
    -- 2. Dikurangi jumlah tiket yang sudah sukses terjual (paid)
    COALESCE(
        (
            SELECT
                COUNT(*)
            FROM
                payments p
            WHERE
                p.event_id = e.id
                AND p.status = 'paid'
                AND p.deleted_at IS NULL
        ),
        0
    ) AS available_quota
FROM
    events e
    JOIN categories c ON e.category_id = c.id
    JOIN users u ON e.user_id = u.id
WHERE
    e.id = ?
    AND e.deleted_at IS NULL
LIMIT
    1
`

type GetEventByIDRow struct {
	ID             uint64
	CategoryID     uint32
	UserID         uint64
	Title          string
	Description    string
	Location       string
	StartTime      time.Time
	EndTime        time.Time
	Status         NullEventsStatus
	CreatedAt      sql.NullTime
	CategoryName   string
	OrganizerName  string
	AvailableQuota int32
}

func (q *Queries) GetEventByID(ctx context.Context, id uint64) (GetEventByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.CategoryName,
		&i.OrganizerName,
		&i.AvailableQuota,
	)
	return i, err
}

const getMyEventByID = `-- name: GetMyEventByID :one
SELECT
    e.id,
    e.title,
    e.description,
    e.location,
    e.start_time,
    e.end_time,
    e.status,
    e.created_at,
    c.name AS category_name,
    u.name AS organizer_name,
    -- 1. Hitung total kuota dari semua jenis tiket di event ini
    COALESCE(
        (
            SELECT
                SUM(tt.quota)
            FROM
                ticket_types tt
            WHERE
                tt.event_id = e.id
        ),
        0
    ) -
    -- 2. Dikurangi total tiket yang sudah terjual (paid)
    COALESCE(
        (
            SELECT
                COUNT(*)
            FROM
                payments p
            WHERE
                p.event_id = e.id
                AND p.status = 'paid'
                AND p.deleted_at IS NULL
        ),
        0
    ) AS available_quota
FROM
    events e
    JOIN categories c ON e.category_id = c.id
    JOIN users u ON e.user_id = u.id
WHERE
    e.id = ?
    AND e.user_id = ?
    AND e.deleted_at IS NULL
    AND c.deleted_at IS NULL
`

type GetMyEventByIDParams struct {
	ID     uint64
	UserID uint64
}

type GetMyEventByIDRow struct {
	ID             uint64
	Title          string
	Description    string
	Location       string
	StartTime      time.Time
	EndTime        time.Time
	Status         NullEventsStatus
	CreatedAt      sql.NullTime
	CategoryName   string
	OrganizerName  string
	AvailableQuota int32
}

func (q *Queries) GetMyEventByID(ctx context.Context, arg GetMyEventByIDParams) (GetMyEventByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getMyEventByID, arg.ID, arg.UserID)
	var i GetMyEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.CreatedAt,
		&i.CategoryName,
		&i.OrganizerName,
		&i.AvailableQuota,
	)
	return i, err
}

const listEventsByStatus = `-- name: ListEventsByStatus :many
SELECT
    e.id,
    e.title,
    e.description,
    e.location,
    e.start_time,
    e.end_time,
    e.status,
    e.created_at,
    c.name AS category_name,
    u.name AS organizer_name,
    -- 1. Hitung total kuota asli dari semua ticket_types di event ini
    COALESCE(
        (
            SELECT
                SUM(tt.quota)
            FROM
                ticket_types tt
            WHERE
                tt.event_id = e.id
        ),
        0
    ) -
    -- 2. Dikurangi jumlah tiket yang sudah sukses terjual (paid)
    COALESCE(
        (
            SELECT
                COUNT(*)
            FROM
                payments p
            WHERE
                p.event_id = e.id
                AND p.status = 'paid'
                AND p.deleted_at IS NULL
        ),
        0
    ) AS available_quota
FROM
    events e
    JOIN categories c ON e.category_id = c.id
    JOIN users u ON e.user_id = u.id
WHERE
    e.status = ?
    AND e.deleted_at IS NULL
    AND c.deleted_at IS NULL
ORDER BY
    e.start_time ASC
LIMIT
    ?
OFFSET
    ?
`

type ListEventsByStatusParams struct {
	Status NullEventsStatus
	Limit  int32
	Offset int32
}

type ListEventsByStatusRow struct {
	ID             uint64
	Title          string
	Description    string
	Location       string
	StartTime      time.Time
	EndTime        time.Time
	Status         NullEventsStatus
	CreatedAt      sql.NullTime
	CategoryName   string
	OrganizerName  string
	AvailableQuota int32
}

func (q *Queries) ListEventsByStatus(ctx context.Context, arg ListEventsByStatusParams) ([]ListEventsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsByStatusRow
	for rows.Next() {
		var i ListEventsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.CategoryName,
			&i.OrganizerName,
			&i.AvailableQuota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyEvents = `-- name: ListMyEvents :many
SELECT
    e.id,
    e.title,
    e.description,
    e.location,
    e.start_time,
    e.end_time,
    e.status,
    e.created_at,
    c.name AS category_name,
    u.name AS organizer_name,
    -- 1. Hitung total kuota asli dari semua ticket_types di event milik saya ini
    COALESCE(
        (
            SELECT
                SUM(tt.quota)
            FROM
                ticket_types tt
            WHERE
                tt.event_id = e.id
        ),
        0
    ) -
    -- 2. Dikurangi jumlah tiket yang sudah sukses terjual (paid)
    COALESCE(
        (
            SELECT
                COUNT(*)
            FROM
                payments p
            WHERE
                p.event_id = e.id
                AND p.status = 'paid'
                AND p.deleted_at IS NULL
        ),
        0
    ) AS available_quota
FROM
    events e
    JOIN categories c ON e.category_id = c.id
    JOIN users u ON e.user_id = u.id
WHERE
    e.user_id = ?
    AND e.deleted_at IS NULL
    AND c.deleted_at IS NULL
ORDER BY
    e.created_at DESC
LIMIT
    ?
OFFSET
    ?
`

type ListMyEventsParams struct {
	UserID uint64
	Limit  int32
	Offset int32
}

type ListMyEventsRow struct {
	ID             uint64
	Title          string
	Description    string
	Location       string
	StartTime      time.Time
	EndTime        time.Time
	Status         NullEventsStatus
	CreatedAt      sql.NullTime
	CategoryName   string
	OrganizerName  string
	AvailableQuota int32
}

func (q *Queries) ListMyEvents(ctx context.Context, arg ListMyEventsParams) ([]ListMyEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMyEvents, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyEventsRow
	for rows.Next() {
		var i ListMyEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.CreatedAt,
			&i.CategoryName,
			&i.OrganizerName,
			&i.AvailableQuota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :exec
UPDATE events
SET
    category_id = ?,
    title = ?,
    description = ?,
    location = ?,
    start_time = ?,
    end_time = ?,
    status = ?
WHERE
    id = ?
    AND deleted_at IS NULL
`

type UpdateEventParams struct {
	CategoryID  uint32
	Title       string
	Description string
	Location    string
	StartTime   time.Time
	EndTime     time.Time
	Status      NullEventsStatus
	ID          uint64
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) error {
	_, err := q.db.ExecContext(ctx, updateEvent,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.ID,
	)
	return err
}

const updateEventStatus = `-- name: UpdateEventStatus :exec
UPDATE events
SET
    status = ?
WHERE
    id = ?
    AND deleted_at IS NULL
`

type UpdateEventStatusParams struct {
	Status NullEventsStatus
	ID     uint64
}

// Dipakai khusus untuk pembatalan (cancel) event oleh admin/organizer
func (q *Queries) UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateEventStatus, arg.Status, arg.ID)
	return err
}
