// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type EventsStatus string

const (
	EventsStatusActive    EventsStatus = "active"
	EventsStatusInactive  EventsStatus = "inactive"
	EventsStatusCancelled EventsStatus = "cancelled"
)

func (e *EventsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventsStatus(s)
	case string:
		*e = EventsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EventsStatus: %T", src)
	}
	return nil
}

type NullEventsStatus struct {
	EventsStatus EventsStatus
	Valid        bool // Valid is true if EventsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EventsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventsStatus), nil
}

type OrdersStatus string

const (
	OrdersStatusPending   OrdersStatus = "pending"
	OrdersStatusPaid      OrdersStatus = "paid"
	OrdersStatusCancelled OrdersStatus = "cancelled"
	OrdersStatusRefunded  OrdersStatus = "refunded"
)

func (e *OrdersStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrdersStatus(s)
	case string:
		*e = OrdersStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrdersStatus: %T", src)
	}
	return nil
}

type NullOrdersStatus struct {
	OrdersStatus OrdersStatus
	Valid        bool // Valid is true if OrdersStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrdersStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrdersStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrdersStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrdersStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrdersStatus), nil
}

type PaymentsStatus string

const (
	PaymentsStatusPending   PaymentsStatus = "pending"
	PaymentsStatusPaid      PaymentsStatus = "paid"
	PaymentsStatusFailed    PaymentsStatus = "failed"
	PaymentsStatusExpired   PaymentsStatus = "expired"
	PaymentsStatusCancelled PaymentsStatus = "cancelled"
	PaymentsStatusRefunded  PaymentsStatus = "refunded"
)

func (e *PaymentsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentsStatus(s)
	case string:
		*e = PaymentsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentsStatus: %T", src)
	}
	return nil
}

type NullPaymentsStatus struct {
	PaymentsStatus PaymentsStatus
	Valid          bool // Valid is true if PaymentsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentsStatus), nil
}

type Category struct {
	ID        uint32
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

type Event struct {
	ID          uint64
	CategoryID  uint32
	UserID      uint64
	Title       string
	Description string
	Location    string
	StartTime   time.Time
	EndTime     time.Time
	Status      NullEventsStatus
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type EventMedium struct {
	ID        uint64
	EventID   uint64
	ImagePath string
	IsPrimary sql.NullBool
	CreatedAt sql.NullTime
}

type Notification struct {
	ID            uint64
	UserID        uint64
	Title         string
	Message       string
	Type          string
	IsRead        bool
	ReferenceType sql.NullString
	ReferenceID   sql.NullInt64
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
}

type Order struct {
	ID          uint64
	UserID      uint64
	TotalAmount uint32
	Status      OrdersStatus
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type OrderItem struct {
	ID           uint64
	OrderID      uint64
	EventID      uint64
	TicketTypeID uint64
	Quantity     uint32
	Price        uint32
}

type Payment struct {
	ID                    uint64
	OrderID               uint64
	PaymentCode           string
	Amount                uint32
	PaymentMethod         string
	PaymentProvider       string
	ProviderTransactionID sql.NullString
	Status                PaymentsStatus
	PaidAt                sql.NullTime
	ExpiredAt             sql.NullTime
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
	DeletedAt             sql.NullTime
}

type Ticket struct {
	ID          uint64
	OrderItemID uint64
	TicketCode  sql.NullString
	QrCode      sql.NullString
	Status      sql.NullString
	CheckedInAt sql.NullTime
}

type TicketType struct {
	ID                uint64
	EventID           uint64
	Name              string
	Price             uint64
	Quota             uint32
	MaxPerTransaction sql.NullInt32
	StartSaleAt       sql.NullTime
	EndSaleAt         sql.NullTime
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
	DeletedAt         sql.NullTime
}

type User struct {
	ID           uint64
	Name         string
	Email        string
	PasswordHash string
	Phone        sql.NullString
	Address      sql.NullString
	Role         string
	IsActive     bool
	RefreshToken sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
