// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type User struct {
	ID           uint64
	Name         string
	Email        string
	PasswordHash string
	Phone        sql.NullString
	Address      sql.NullString
	Role         string
	IsActive     bool
	RefreshToken sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
