// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type User struct {
	ID           sql.NullInt64
	Name         string
	Email        string
	PasswordHash string
	Phone        sql.NullString
	Address      sql.NullString
	Role         string
	IsActive     bool
	RefreshToken sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}
