// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package database

import (
	"context"
	"database/sql"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT
    COUNT(*)
FROM
    notifications
WHERE
    user_id = ?
    AND is_read = FALSE
    AND deleted_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :execresult
INSERT INTO
    notifications (
        user_id,
        title,
        message,
        type,
        is_read,
        reference_type,
        reference_id
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?)
`

type CreateNotificationParams struct {
	UserID        uint64
	Title         string
	Message       string
	Type          string
	IsRead        bool
	ReferenceType sql.NullString
	ReferenceID   sql.NullInt64
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createNotification,
		arg.UserID,
		arg.Title,
		arg.Message,
		arg.Type,
		arg.IsRead,
		arg.ReferenceType,
		arg.ReferenceID,
	)
}

const deleteNotification = `-- name: DeleteNotification :exec
UPDATE notifications
SET
    deleted_at = CURRENT_TIMESTAMP
WHERE
    id = ?
    AND deleted_at IS NULL
`

func (q *Queries) DeleteNotification(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteNotification, id)
	return err
}

const deleteNotificationsByUserID = `-- name: DeleteNotificationsByUserID :exec
UPDATE notifications
SET
    deleted_at = CURRENT_TIMESTAMP
WHERE
    user_id = ?
    AND deleted_at IS NULL
`

func (q *Queries) DeleteNotificationsByUserID(ctx context.Context, userID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationsByUserID, userID)
	return err
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT
    id,
    user_id,
    title,
    message,
    type,
    is_read,
    reference_type,
    reference_id,
    created_at,
    updated_at,
    deleted_at
FROM
    notifications
WHERE
    id = ?
    AND deleted_at IS NULL
LIMIT
    1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id uint64) (Notification, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Message,
		&i.Type,
		&i.IsRead,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listNotificationsByUserID = `-- name: ListNotificationsByUserID :many
SELECT
    id,
    user_id,
    title,
    message,
    type,
    is_read,
    reference_type,
    reference_id,
    created_at,
    updated_at,
    deleted_at
FROM
    notifications
WHERE
    user_id = ?
    AND deleted_at IS NULL
ORDER BY
    created_at DESC
LIMIT
    ?
OFFSET
    ?
`

type ListNotificationsByUserIDParams struct {
	UserID uint64
	Limit  int32
	Offset int32
}

func (q *Queries) ListNotificationsByUserID(ctx context.Context, arg ListNotificationsByUserIDParams) ([]Notification, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.IsRead,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET
    is_read = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE
    user_id = ?
    AND deleted_at IS NULL
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, userID uint64) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsAsRead, userID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :exec
UPDATE notifications
SET
    is_read = TRUE,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
    AND deleted_at IS NULL
`

func (q *Queries) MarkNotificationAsRead(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, markNotificationAsRead, id)
	return err
}
