// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package database

import (
	"context"
	"database/sql"
)

const countOrders = `-- name: CountOrders :one
SELECT COUNT(*)
FROM orders
WHERE
    deleted_at IS NULL
`

func (q *Queries) CountOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrdersByUserID = `-- name: CountOrdersByUserID :one
SELECT COUNT(*)
FROM orders
WHERE
    user_id = ?
    AND deleted_at IS NULL
`

func (q *Queries) CountOrdersByUserID(ctx context.Context, userID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrdersByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :execresult
INSERT INTO orders (
    user_id,
    total_amount,
    status
)
VALUES (
    ?, ?, ?
)
`

type CreateOrderParams struct {
	UserID      uint64
	TotalAmount uint32
	Status      OrdersStatus
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrder, arg.UserID, arg.TotalAmount, arg.Status)
}

const deleteOrder = `-- name: DeleteOrder :exec
UPDATE orders
SET
    deleted_at = CURRENT_TIMESTAMP
WHERE
    id = ?
    AND deleted_at IS NULL
`

func (q *Queries) DeleteOrder(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteOrder, id)
	return err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
    id,
    user_id,
    total_amount,
    status,
    created_at,
    updated_at,
    deleted_at
FROM orders
WHERE
    id = ?
    AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id uint64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT
    id,
    user_id,
    total_amount,
    status,
    created_at,
    updated_at,
    deleted_at
FROM orders
WHERE
    user_id = ?
    AND deleted_at IS NULL
ORDER BY
    created_at DESC
LIMIT ?
OFFSET ?
`

type ListOrdersByUserIDParams struct {
	UserID uint64
	Limit  int32
	Offset int32
}

func (q *Queries) ListOrdersByUserID(ctx context.Context, arg ListOrdersByUserIDParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrdersByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
    AND deleted_at IS NULL
`

type UpdateOrderStatusParams struct {
	Status OrdersStatus
	ID     uint64
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.ID)
	return err
}
