// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order_item.sql

package database

import (
	"context"
	"database/sql"
)

const countOrderItemsByOrderID = `-- name: CountOrderItemsByOrderID :one
SELECT
    COUNT(*)
FROM
    order_items
WHERE
    order_id = ?
`

func (q *Queries) CountOrderItemsByOrderID(ctx context.Context, orderID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOrderItemsByOrderID, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrderItem = `-- name: CreateOrderItem :execresult
INSERT INTO
    order_items (
        order_id,
        event_id,
        ticket_type_id,
        quantity,
        price
    )
VALUES
    (?, ?, ?, ?, ?)
`

type CreateOrderItemParams struct {
	OrderID      uint64
	EventID      uint64
	TicketTypeID uint64
	Quantity     uint32
	Price        uint32
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOrderItem,
		arg.OrderID,
		arg.EventID,
		arg.TicketTypeID,
		arg.Quantity,
		arg.Price,
	)
}

const deleteOrderItem = `-- name: DeleteOrderItem :exec
DELETE FROM order_items
WHERE
    id = ?
`

func (q *Queries) DeleteOrderItem(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteOrderItem, id)
	return err
}

const deleteOrderItemsByOrderID = `-- name: DeleteOrderItemsByOrderID :exec
DELETE FROM order_items
WHERE
    order_id = ?
`

func (q *Queries) DeleteOrderItemsByOrderID(ctx context.Context, orderID uint64) error {
	_, err := q.db.ExecContext(ctx, deleteOrderItemsByOrderID, orderID)
	return err
}

const getOrderItemByID = `-- name: GetOrderItemByID :one
SELECT
    id,
    order_id,
    event_id,
    ticket_type_id,
    quantity,
    price
FROM
    order_items
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetOrderItemByID(ctx context.Context, id uint64) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, getOrderItemByID, id)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.EventID,
		&i.TicketTypeID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT
    id,
    order_id,
    event_id,
    ticket_type_id,
    quantity,
    price
FROM
    order_items
WHERE
    order_id = ?
ORDER BY
    id ASC
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID uint64) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.EventID,
			&i.TicketTypeID,
			&i.Quantity,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
