// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package database

import (
	"context"
	"database/sql"
)

const countPayments = `-- name: CountPayments :one
SELECT COUNT(*)
FROM payments
WHERE
    deleted_at IS NULL
`

func (q *Queries) CountPayments(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPayments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :execresult
INSERT INTO payments (
    order_id,
    payment_code,
    amount,
    payment_method,
    payment_provider,
    provider_transaction_id,
    status,
    paid_at,
    expired_at
)
VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type CreatePaymentParams struct {
	OrderID               uint64
	PaymentCode           string
	Amount                uint32
	PaymentMethod         string
	PaymentProvider       string
	ProviderTransactionID sql.NullString
	Status                PaymentsStatus
	PaidAt                sql.NullTime
	ExpiredAt             sql.NullTime
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPayment,
		arg.OrderID,
		arg.PaymentCode,
		arg.Amount,
		arg.PaymentMethod,
		arg.PaymentProvider,
		arg.ProviderTransactionID,
		arg.Status,
		arg.PaidAt,
		arg.ExpiredAt,
	)
}

const deletePayment = `-- name: DeletePayment :exec
UPDATE payments
SET
    deleted_at = CURRENT_TIMESTAMP
WHERE
    id = ?
    AND deleted_at IS NULL
`

func (q *Queries) DeletePayment(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deletePayment, id)
	return err
}

const getPaymentByCode = `-- name: GetPaymentByCode :one
SELECT
    id,
    order_id,
    payment_code,
    amount,
    payment_method,
    payment_provider,
    provider_transaction_id,
    status,
    paid_at,
    expired_at,
    created_at,
    updated_at,
    deleted_at
FROM payments
WHERE
    payment_code = ?
    AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPaymentByCode(ctx context.Context, paymentCode string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByCode, paymentCode)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentCode,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentProvider,
		&i.ProviderTransactionID,
		&i.Status,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT
    id,
    order_id,
    payment_code,
    amount,
    payment_method,
    payment_provider,
    provider_transaction_id,
    status,
    paid_at,
    expired_at,
    created_at,
    updated_at,
    deleted_at
FROM payments
WHERE
    id = ?
    AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uint64) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentCode,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentProvider,
		&i.ProviderTransactionID,
		&i.Status,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT
    id,
    order_id,
    payment_code,
    amount,
    payment_method,
    payment_provider,
    provider_transaction_id,
    status,
    paid_at,
    expired_at,
    created_at,
    updated_at,
    deleted_at
FROM payments
WHERE
    order_id = ?
    AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID uint64) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentCode,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentProvider,
		&i.ProviderTransactionID,
		&i.Status,
		&i.PaidAt,
		&i.ExpiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT
    id,
    order_id,
    payment_code,
    amount,
    payment_method,
    payment_provider,
    provider_transaction_id,
    status,
    paid_at,
    expired_at,
    created_at,
    updated_at,
    deleted_at
FROM payments
WHERE
    deleted_at IS NULL
ORDER BY
    created_at DESC
LIMIT ?
OFFSET ?
`

type ListPaymentsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPayments(ctx context.Context, arg ListPaymentsParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPayments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PaymentCode,
			&i.Amount,
			&i.PaymentMethod,
			&i.PaymentProvider,
			&i.ProviderTransactionID,
			&i.Status,
			&i.PaidAt,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByUserID = `-- name: ListPaymentsByUserID :many
SELECT
    p.id,
    p.order_id,
    p.payment_code,
    p.amount,
    p.payment_method,
    p.payment_provider,
    p.provider_transaction_id,
    p.status,
    p.paid_at,
    p.expired_at,
    p.created_at,
    p.updated_at,
    p.deleted_at
FROM payments p
JOIN orders o ON o.id = p.order_id
WHERE
    o.user_id = ?
    AND p.deleted_at IS NULL
ORDER BY
    p.created_at DESC
LIMIT ?
OFFSET ?
`

type ListPaymentsByUserIDParams struct {
	UserID uint64
	Limit  int32
	Offset int32
}

func (q *Queries) ListPaymentsByUserID(ctx context.Context, arg ListPaymentsByUserIDParams) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.PaymentCode,
			&i.Amount,
			&i.PaymentMethod,
			&i.PaymentProvider,
			&i.ProviderTransactionID,
			&i.Status,
			&i.PaidAt,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentAsPaid = `-- name: MarkPaymentAsPaid :exec
UPDATE payments
SET
    status = 'paid',
    paid_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
    AND deleted_at IS NULL
`

func (q *Queries) MarkPaymentAsPaid(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, markPaymentAsPaid, id)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments
SET
    status = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
    AND deleted_at IS NULL
`

type UpdatePaymentStatusParams struct {
	Status PaymentsStatus
	ID     uint64
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentStatus, arg.Status, arg.ID)
	return err
}

const updateProviderTransactionID = `-- name: UpdateProviderTransactionID :exec
UPDATE payments
SET
    provider_transaction_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
    AND deleted_at IS NULL
`

type UpdateProviderTransactionIDParams struct {
	ProviderTransactionID sql.NullString
	ID                    uint64
}

func (q *Queries) UpdateProviderTransactionID(ctx context.Context, arg UpdateProviderTransactionIDParams) error {
	_, err := q.db.ExecContext(ctx, updateProviderTransactionID, arg.ProviderTransactionID, arg.ID)
	return err
}
