// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket.sql

package database

import (
	"context"
	"database/sql"
)

const checkInTicket = `-- name: CheckInTicket :exec
UPDATE tickets
SET
    status = 'used',
    checked_in_at = CURRENT_TIMESTAMP
WHERE
    id = ?
`

func (q *Queries) CheckInTicket(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, checkInTicket, id)
	return err
}

const countTicketsByOrderItemID = `-- name: CountTicketsByOrderItemID :one
SELECT
    COUNT(*)
FROM
    tickets
WHERE
    order_item_id = ?
`

func (q *Queries) CountTicketsByOrderItemID(ctx context.Context, orderItemID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTicketsByOrderItemID, orderItemID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicket = `-- name: CreateTicket :execresult
INSERT INTO
    tickets (
        order_item_id,
        ticket_code,
        qr_code,
        status,
        checked_in_at
    )
VALUES
    (?, ?, ?, ?, ?)
`

type CreateTicketParams struct {
	OrderItemID uint64
	TicketCode  string
	QrCode      string
	Status      TicketsStatus
	CheckedInAt sql.NullTime
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTicket,
		arg.OrderItemID,
		arg.TicketCode,
		arg.QrCode,
		arg.Status,
		arg.CheckedInAt,
	)
}

const deleteTicket = `-- name: DeleteTicket :exec
DELETE FROM tickets
WHERE
    id = ?
`

func (q *Queries) DeleteTicket(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteTicket, id)
	return err
}

const getTicketByCode = `-- name: GetTicketByCode :one
SELECT
    id,
    order_item_id,
    ticket_code,
    qr_code,
    status,
    checked_in_at
FROM
    tickets
WHERE
    ticket_code = ?
LIMIT
    1
`

func (q *Queries) GetTicketByCode(ctx context.Context, ticketCode string) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketByCode, ticketCode)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.TicketCode,
		&i.QrCode,
		&i.Status,
		&i.CheckedInAt,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT
    id,
    order_item_id,
    ticket_code,
    qr_code,
    status,
    checked_in_at
FROM
    tickets
WHERE
    id = ?
LIMIT
    1
`

func (q *Queries) GetTicketByID(ctx context.Context, id uint64) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.OrderItemID,
		&i.TicketCode,
		&i.QrCode,
		&i.Status,
		&i.CheckedInAt,
	)
	return i, err
}

const listTicketsByOrderItemID = `-- name: ListTicketsByOrderItemID :many
SELECT
    id,
    order_item_id,
    ticket_code,
    qr_code,
    status,
    checked_in_at
FROM
    tickets
WHERE
    order_item_id = ?
ORDER BY
    id ASC
`

func (q *Queries) ListTicketsByOrderItemID(ctx context.Context, orderItemID uint64) ([]Ticket, error) {
	rows, err := q.db.QueryContext(ctx, listTicketsByOrderItemID, orderItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.OrderItemID,
			&i.TicketCode,
			&i.QrCode,
			&i.Status,
			&i.CheckedInAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketQRCode = `-- name: UpdateTicketQRCode :exec
UPDATE tickets
SET
    qr_code = ?
WHERE
    id = ?
`

type UpdateTicketQRCodeParams struct {
	QrCode string
	ID     uint64
}

func (q *Queries) UpdateTicketQRCode(ctx context.Context, arg UpdateTicketQRCodeParams) error {
	_, err := q.db.ExecContext(ctx, updateTicketQRCode, arg.QrCode, arg.ID)
	return err
}

const updateTicketStatus = `-- name: UpdateTicketStatus :exec
UPDATE tickets
SET
    status = ?
WHERE
    id = ?
`

type UpdateTicketStatusParams struct {
	Status TicketsStatus
	ID     uint64
}

func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTicketStatus, arg.Status, arg.ID)
	return err
}
