// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const bookTicket = `-- name: BookTicket :execresult
INSERT INTO
    tickets (event_id, user_id, ticket_code, status)
VALUES
    (?, ?, ?, ?)
`

type BookTicketParams struct {
	EventID    uint64
	UserID     uint64
	TicketCode string
	Status     NullTicketsStatus
}

// Dipakai saat warga klik "Booking" (Status default: 'booked')
func (q *Queries) BookTicket(ctx context.Context, arg BookTicketParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, bookTicket,
		arg.EventID,
		arg.UserID,
		arg.TicketCode,
		arg.Status,
	)
}

const getTicketByCode = `-- name: GetTicketByCode :one
SELECT
    t.id,
    t.event_id,
    t.user_id,
    t.ticket_code,
    t.status,
    t.created_at,
    e.title AS event_title,
    e.start_time AS event_start_time,
    u.name AS attendee_name
FROM
    tickets t
    JOIN events e ON t.event_id = e.id
    JOIN users u ON t.user_id = u.id
WHERE
    t.ticket_code = ?
    AND t.deleted_at IS NULL
LIMIT
    1
`

type GetTicketByCodeRow struct {
	ID             uint64
	EventID        uint64
	UserID         uint64
	TicketCode     string
	Status         NullTicketsStatus
	CreatedAt      time.Time
	EventTitle     string
	EventStartTime time.Time
	AttendeeName   string
}

// Dipakai pas panitia nge-scan QR Code tiket di gerbang masuk
func (q *Queries) GetTicketByCode(ctx context.Context, ticketCode string) (GetTicketByCodeRow, error) {
	row := q.db.QueryRowContext(ctx, getTicketByCode, ticketCode)
	var i GetTicketByCodeRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.TicketCode,
		&i.Status,
		&i.CreatedAt,
		&i.EventTitle,
		&i.EventStartTime,
		&i.AttendeeName,
	)
	return i, err
}

const hardDeleteTicket = `-- name: HardDeleteTicket :exec
DELETE FROM tickets
WHERE
    id = ?
`

// Hapus fisik dari disk (Khusus clean up data testing)
func (q *Queries) HardDeleteTicket(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, hardDeleteTicket, id)
	return err
}

const listMyTickets = `-- name: ListMyTickets :many
SELECT
    t.id,
    t.ticket_code,
    t.status,
    t.created_at,
    e.title AS event_title,
    e.location AS event_location,
    e.start_time AS event_start_time
FROM
    tickets t
    JOIN events e ON t.event_id = e.id
WHERE
    t.user_id = ?
    AND t.deleted_at IS NULL
ORDER BY
    t.created_at DESC
`

type ListMyTicketsRow struct {
	ID             uint64
	TicketCode     string
	Status         NullTicketsStatus
	CreatedAt      time.Time
	EventTitle     string
	EventLocation  string
	EventStartTime time.Time
}

// Dipakai di aplikasi mobile/web warga buat lihat daftar tiket yang mereka beli
func (q *Queries) ListMyTickets(ctx context.Context, userID uint64) ([]ListMyTicketsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMyTickets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyTicketsRow
	for rows.Next() {
		var i ListMyTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketCode,
			&i.Status,
			&i.CreatedAt,
			&i.EventTitle,
			&i.EventLocation,
			&i.EventStartTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTicket = `-- name: SoftDeleteTicket :exec
UPDATE tickets
SET
    deleted_at = NOW(),
    status = 'cancelled'
WHERE
    id = ?
`

// Membatalkan tiket tanpa menghapus history finansial
func (q *Queries) SoftDeleteTicket(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, softDeleteTicket, id)
	return err
}

const updateTicketStatus = `-- name: UpdateTicketStatus :exec
UPDATE tickets
SET
    status = ?,
    updated_at = NOW()
WHERE
    id = ?
    AND deleted_at IS NULL
`

type UpdateTicketStatusParams struct {
	Status NullTicketsStatus
	ID     uint64
}

// Dipakai pas pembayaran lunas ('paid') atau pas tiket di-scan masuk ('used')
func (q *Queries) UpdateTicketStatus(ctx context.Context, arg UpdateTicketStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTicketStatus, arg.Status, arg.ID)
	return err
}
