// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_type.sql

package database

import (
	"context"
	"database/sql"
)

const countTicketTypesByEventID = `-- name: CountTicketTypesByEventID :one
SELECT
    COUNT(*)
FROM
    ticket_types
WHERE
    event_id = ?
    AND deleted_at IS NULL
`

func (q *Queries) CountTicketTypesByEventID(ctx context.Context, eventID uint64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTicketTypesByEventID, eventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTicketType = `-- name: CreateTicketType :execresult
INSERT INTO
    ticket_types (
        event_id,
        name,
        price,
        quota,
        max_per_transaction,
        start_sale_at,
        end_sale_at
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?)
`

type CreateTicketTypeParams struct {
	EventID           uint64
	Name              string
	Price             uint64
	Quota             uint32
	MaxPerTransaction sql.NullInt32
	StartSaleAt       sql.NullTime
	EndSaleAt         sql.NullTime
}

func (q *Queries) CreateTicketType(ctx context.Context, arg CreateTicketTypeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTicketType,
		arg.EventID,
		arg.Name,
		arg.Price,
		arg.Quota,
		arg.MaxPerTransaction,
		arg.StartSaleAt,
		arg.EndSaleAt,
	)
}

const deleteTicketType = `-- name: DeleteTicketType :exec
UPDATE ticket_types
SET
    deleted_at = CURRENT_TIMESTAMP
WHERE
    id = ?
    AND deleted_at IS NULL
`

func (q *Queries) DeleteTicketType(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteTicketType, id)
	return err
}

const getAvailableTicketTypeByID = `-- name: GetAvailableTicketTypeByID :one
SELECT
    id,
    event_id,
    name,
    price,
    quota,
    max_per_transaction,
    start_sale_at,
    end_sale_at,
    created_at,
    updated_at
FROM
    ticket_types
WHERE
    id = ?
    AND deleted_at IS NULL
    AND (
        start_sale_at IS NULL
        OR start_sale_at <= ?
    )
    AND (
        end_sale_at IS NULL
        OR end_sale_at >= ?
    )
LIMIT
    1
`

type GetAvailableTicketTypeByIDParams struct {
	ID          uint64
	StartSaleAt sql.NullTime
	EndSaleAt   sql.NullTime
}

type GetAvailableTicketTypeByIDRow struct {
	ID                uint64
	EventID           uint64
	Name              string
	Price             uint64
	Quota             uint32
	MaxPerTransaction sql.NullInt32
	StartSaleAt       sql.NullTime
	EndSaleAt         sql.NullTime
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

func (q *Queries) GetAvailableTicketTypeByID(ctx context.Context, arg GetAvailableTicketTypeByIDParams) (GetAvailableTicketTypeByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAvailableTicketTypeByID, arg.ID, arg.StartSaleAt, arg.EndSaleAt)
	var i GetAvailableTicketTypeByIDRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.Quota,
		&i.MaxPerTransaction,
		&i.StartSaleAt,
		&i.EndSaleAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketTypeByID = `-- name: GetTicketTypeByID :one
SELECT
    id,
    event_id,
    name,
    price,
    quota,
    max_per_transaction,
    start_sale_at,
    end_sale_at,
    created_at,
    updated_at
FROM
    ticket_types
WHERE
    id = ?
    AND deleted_at IS NULL
LIMIT
    1
`

type GetTicketTypeByIDRow struct {
	ID                uint64
	EventID           uint64
	Name              string
	Price             uint64
	Quota             uint32
	MaxPerTransaction sql.NullInt32
	StartSaleAt       sql.NullTime
	EndSaleAt         sql.NullTime
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

func (q *Queries) GetTicketTypeByID(ctx context.Context, id uint64) (GetTicketTypeByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTicketTypeByID, id)
	var i GetTicketTypeByIDRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Name,
		&i.Price,
		&i.Quota,
		&i.MaxPerTransaction,
		&i.StartSaleAt,
		&i.EndSaleAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTicketTypes = `-- name: ListActiveTicketTypes :many
SELECT
    id,
    event_id,
    name,
    price,
    quota,
    max_per_transaction,
    start_sale_at,
    end_sale_at,
    created_at,
    updated_at
FROM
    ticket_types
WHERE
    event_id = ?
    AND deleted_at IS NULL
    AND (
        start_sale_at IS NULL
        OR start_sale_at <= ?
    )
    AND (
        end_sale_at IS NULL
        OR end_sale_at >= ?
    )
ORDER BY
    price ASC
`

type ListActiveTicketTypesParams struct {
	EventID     uint64
	StartSaleAt sql.NullTime
	EndSaleAt   sql.NullTime
}

type ListActiveTicketTypesRow struct {
	ID                uint64
	EventID           uint64
	Name              string
	Price             uint64
	Quota             uint32
	MaxPerTransaction sql.NullInt32
	StartSaleAt       sql.NullTime
	EndSaleAt         sql.NullTime
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

func (q *Queries) ListActiveTicketTypes(ctx context.Context, arg ListActiveTicketTypesParams) ([]ListActiveTicketTypesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTicketTypes, arg.EventID, arg.StartSaleAt, arg.EndSaleAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTicketTypesRow
	for rows.Next() {
		var i ListActiveTicketTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Price,
			&i.Quota,
			&i.MaxPerTransaction,
			&i.StartSaleAt,
			&i.EndSaleAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketTypesByEventID = `-- name: ListTicketTypesByEventID :many
SELECT
    id,
    event_id,
    name,
    price,
    quota,
    max_per_transaction,
    start_sale_at,
    end_sale_at,
    created_at,
    updated_at
FROM
    ticket_types
WHERE
    event_id = ?
    AND deleted_at IS NULL
ORDER BY
    created_at ASC
LIMIT
    ?
OFFSET
    ?
`

type ListTicketTypesByEventIDParams struct {
	EventID uint64
	Limit   int32
	Offset  int32
}

type ListTicketTypesByEventIDRow struct {
	ID                uint64
	EventID           uint64
	Name              string
	Price             uint64
	Quota             uint32
	MaxPerTransaction sql.NullInt32
	StartSaleAt       sql.NullTime
	EndSaleAt         sql.NullTime
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

func (q *Queries) ListTicketTypesByEventID(ctx context.Context, arg ListTicketTypesByEventIDParams) ([]ListTicketTypesByEventIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listTicketTypesByEventID, arg.EventID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketTypesByEventIDRow
	for rows.Next() {
		var i ListTicketTypesByEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Name,
			&i.Price,
			&i.Quota,
			&i.MaxPerTransaction,
			&i.StartSaleAt,
			&i.EndSaleAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketType = `-- name: UpdateTicketType :exec
UPDATE ticket_types
SET
    name = ?,
    price = ?,
    quota = ?,
    max_per_transaction = ?,
    start_sale_at = ?,
    end_sale_at = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE
    id = ?
    AND deleted_at IS NULL
`

type UpdateTicketTypeParams struct {
	Name              string
	Price             uint64
	Quota             uint32
	MaxPerTransaction sql.NullInt32
	StartSaleAt       sql.NullTime
	EndSaleAt         sql.NullTime
	ID                uint64
}

func (q *Queries) UpdateTicketType(ctx context.Context, arg UpdateTicketTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateTicketType,
		arg.Name,
		arg.Price,
		arg.Quota,
		arg.MaxPerTransaction,
		arg.StartSaleAt,
		arg.EndSaleAt,
		arg.ID,
	)
	return err
}
