// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) as total
FROM users 
WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
    name, 
    email, 
    password_hash,
    phone,
    address,
    role,
    is_active,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, NOW(), NOW()
)
`

type CreateUserParams struct {
	Name         string
	Email        string
	PasswordHash string
	Phone        sql.NullString
	Address      sql.NullString
	Role         string
	IsActive     bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Phone,
		arg.Address,
		arg.Role,
		arg.IsActive,
	)
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users 
SET 
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getActiveUsers = `-- name: GetActiveUsers :many
SELECT 
    id,
    name,
    email,
    role,
    created_at
FROM users 
WHERE is_active = true AND deleted_at IS NULL
ORDER BY created_at DESC
`

type GetActiveUsersRow struct {
	ID        uint64
	Name      string
	Email     string
	Role      string
	CreatedAt time.Time
}

func (q *Queries) GetActiveUsers(ctx context.Context) ([]GetActiveUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveUsersRow
	for rows.Next() {
		var i GetActiveUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT 
    id,
    name,
    email,
    password_hash,
    phone,
    address,
    role,
    is_active,
    created_at,
    updated_at
FROM users 
WHERE email = ? AND deleted_at IS NULL
`

type GetUserByEmailRow struct {
	ID           uint64
	Name         string
	Email        string
	PasswordHash string
	Phone        sql.NullString
	Address      sql.NullString
	Role         string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.Phone,
		&i.Address,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT 
    id,
    name,
    email,
    phone,
    address,
    role,
    is_active,
    created_at,
    updated_at
FROM users 
WHERE id = ? AND deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID        uint64
	Name      string
	Email     string
	Phone     sql.NullString
	Address   sql.NullString
	Role      string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id uint64) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.Role,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByRefreshToken = `-- name: GetUserByRefreshToken :one
SELECT 
    id,
    name,
    email,
    role,
    is_active
FROM users 
WHERE refresh_token = ? AND deleted_at IS NULL
`

type GetUserByRefreshTokenRow struct {
	ID       uint64
	Name     string
	Email    string
	Role     string
	IsActive bool
}

func (q *Queries) GetUserByRefreshToken(ctx context.Context, refreshToken sql.NullString) (GetUserByRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByRefreshToken, refreshToken)
	var i GetUserByRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.IsActive,
	)
	return i, err
}

const hardDeleteUser = `-- name: HardDeleteUser :exec
DELETE FROM users 
WHERE id = ?
`

func (q *Queries) HardDeleteUser(ctx context.Context, id uint64) error {
	_, err := q.db.ExecContext(ctx, hardDeleteUser, id)
	return err
}

const listUsers = `-- name: ListUsers :many
SELECT 
    id,
    name,
    email,
    phone,
    address,
    role,
    is_active,
    created_at,
    updated_at
FROM users 
WHERE deleted_at IS NULL
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

type ListUsersRow struct {
	ID        uint64
	Name      string
	Email     string
	Phone     sql.NullString
	Address   sql.NullString
	Role      string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT 
    id,
    name,
    email,
    phone,
    address,
    role,
    is_active,
    created_at,
    updated_at
FROM users 
WHERE deleted_at IS NULL
    AND (name LIKE ? OR email LIKE ?)
ORDER BY id DESC
LIMIT ? OFFSET ?
`

type SearchUsersParams struct {
	Name   string
	Email  string
	Limit  int32
	Offset int32
}

type SearchUsersRow struct {
	ID        uint64
	Name      string
	Email     string
	Phone     sql.NullString
	Address   sql.NullString
	Role      string
	IsActive  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUsers,
		arg.Name,
		arg.Email,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Address,
			&i.Role,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users 
SET 
    name = ?,
    phone = ?,
    address = ?,
    updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserParams struct {
	Name    string
	Phone   sql.NullString
	Address sql.NullString
	ID      uint64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Phone,
		arg.Address,
		arg.ID,
	)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users 
SET 
    email = ?,
    updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserEmailParams struct {
	Email string
	ID    uint64
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmail, arg.Email, arg.ID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users 
SET 
    password_hash = ?,
    updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           uint64
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserRefreshToken = `-- name: UpdateUserRefreshToken :exec
UPDATE users 
SET 
    refresh_token = ?,
    updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserRefreshTokenParams struct {
	RefreshToken sql.NullString
	ID           uint64
}

func (q *Queries) UpdateUserRefreshToken(ctx context.Context, arg UpdateUserRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRefreshToken, arg.RefreshToken, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users 
SET 
    role = ?,
    updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserRoleParams struct {
	Role string
	ID   uint64
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users 
SET 
    is_active = ?,
    updated_at = NOW()
WHERE id = ? AND deleted_at IS NULL
`

type UpdateUserStatusParams struct {
	IsActive bool
	ID       uint64
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.IsActive, arg.ID)
	return err
}
