// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"go-fwgin/internal/config"
	"go-fwgin/internal/database"
	"go-fwgin/internal/modules/user"
)

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := config.NewMySQL(configConfig)
	if err != nil {
		return nil, nil, err
	}
	queries := database.New(db)
	repositoryUser := user.NewRepositoryUser(queries)
	userService := user.NewServiceUser(repositoryUser, configConfig)
	handlerUser := user.NewHandleUser(userService)
	app := &App{
		Config:      configConfig,
		UserHandler: handlerUser,
	}
	return app, func() {
		cleanup()
	}, nil
}
