// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package bootstrap

import (
	"go-fwgin/internal/config"
	"go-fwgin/internal/database"
	"go-fwgin/internal/modules/category"
	"go-fwgin/internal/modules/user"
)

// Injectors from wire.go:

func InitializeApp() (*App, func(), error) {
	configConfig, err := config.LoadConfig()
	if err != nil {
		return nil, nil, err
	}
	db, cleanup, err := config.NewMySQL(configConfig)
	if err != nil {
		return nil, nil, err
	}
	queries := database.New(db)
	userRepository := user.NewRepositoryUser(queries)
	userService := user.NewServiceUser(userRepository, configConfig)
	handlerUser := user.NewHandleUser(userService)
	categoryRepository := category.NewRepositoryCategory(queries)
	categoryService := category.NewServiceCategory(categoryRepository)
	handlerCategory := category.NewHandlerCategory(categoryService)
	app := &App{
		Config:          configConfig,
		UserHandler:     handlerUser,
		CategoryHandler: handlerCategory,
	}
	return app, func() {
		cleanup()
	}, nil
}
